to-do-list/Models/ErrorViewModel.cs
namespace to_do_list.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

to-do-list/Models/Priority.cs
namespace to_do_list.Models
{
    public enum Priority
    {
        None = 0,
        Low,
        Medium,
        High
    }
}

to-do-list/Models/Task.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace to_do_list.Models
{
    public class Task
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(150)]
        public string? Description { get; set; }
        public Priority Priority { get; set; }
        [AllowNull]
        public DateTime? Deadline { get; set; }
        public bool IsCompleted { get; set; }
    }
}

to-do-list/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using to_do_list.Models;

namespace to_do_list.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

to-do-list/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using to_do_list.Data;

namespace to_do_list.Controllers
{
    public class TaskController : Controller
    {
        private readonly ApplicationDBContext _db;

        public TaskController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Models.Task> tasksList = _db.Tasks;
            return View(tasksList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Models.Task task)
        {
            if(task.Deadline.HasValue && task.Deadline <=  DateTime.UtcNow)
            {
                ModelState.AddModelError("deadline", "Deadline must be later than currend date and time.");
            }
            if (ModelState.IsValid)
            {
                _db.Tasks.Add(task);
                _db.SaveChanges();
                TempData["success"] = "Task created successfully";
                return RedirectToAction("Index");
            }
            return View(task);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0) 
            {
                return NotFound();
            }
            
            var taskToEdit = _db.Tasks.Find(id);

            if(taskToEdit == null)
            {
                return NotFound();
            }

            return View(taskToEdit);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Models.Task task)
        {
            if (task.Deadline.HasValue && task.Deadline <= DateTime.UtcNow)
            {
                ModelState.AddModelError("deadline", "Deadline must be later than currend date and time.");
            }
            if (ModelState.IsValid)
            {
                _db.Tasks.Update(task);
                _db.SaveChanges();
                TempData["success"] = "Task updated successfully";
                return RedirectToAction("Index");
            }
            return View(task);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var taskToDelete = _db.Tasks.Find(id);

            if (taskToDelete == null)
            {
                return NotFound();
            }

            return View(taskToDelete);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var taskToDelete = _db.Tasks.Find(id);

            if (taskToDelete == null)
            {
                return NotFound();
            }

            _db.Tasks.Remove(taskToDelete);
            _db.SaveChanges();
            TempData["success"] = "Task deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

to-do-list/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

to-do-list/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - to_do_list</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/to_do_list.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark" style="bottom:0; position:fixed; width:100%">
        <div class="container" style="padding:12px">
            &copy; 2024 - to_do_list - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

to-do-list/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

to-do-list/Views/Task/Create.cshtml
@model to_do_list.Models.Task

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label> &nbsp;
            <select asp-for="Priority" asp-items="Html.GetEnumSelectList<Priority>()"></select>
        </div>
        <div class="mb-3">
            <label asp-for="Deadline"></label>
            <input asp-for="Deadline" class="form-control" />
            <span asp-validation-for="Deadline" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Task" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Tasks</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

to-do-list/Views/Task/Delete.cshtml
@model to_do_list.Models.Task

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label> &nbsp;
            <select asp-for="Priority" asp-items="Html.GetEnumSelectList<Priority>()" disabled></select>
        </div>
        <div class="mb-3">
            <label asp-for="Deadline"></label>
            <input asp-for="Deadline" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Task" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Tasks</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

to-do-list/Views/Task/Edit.cshtml
@model to_do_list.Models.Task

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label> &nbsp;
            <select asp-for="Priority" asp-items="Html.GetEnumSelectList<Priority>()"></select>
        </div>
        <div class="mb-3">
            <label asp-for="Deadline"></label>
            <input asp-for="Deadline" class="form-control" />
            <span asp-validation-for="Deadline" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Task" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Tasks</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

to-do-list/Views/Task/Index.cshtml
@model IEnumerable<to_do_list.Models.Task>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Task List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Task" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; Create New Task
            </a>
        </div>
    </div>
    <br />

    <table class="table table-bordered table-striped table-dark" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Deadline</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td>
                        @obj.Name
                    </td>
                    <td>
                        @obj.Description
                    </td>
                    <td>
                        @obj.Priority
                    </td>
                    <td>
                        @obj.Deadline
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Task" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Task" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-x-square"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>